### ISSUE TITLE
Entrypoint needs to be able to import lb certificate into cacerts

### ISSUE THREAD

**Issue by hoeghh** [Praqma/jira-server#4]
Im getting these in the logs, as im using a self signed cert: 

```
2018-05-01 10:38:18,420 http-nio-8080-exec-5 ERROR hoeghh 638x177x1 197uri4 192.168.50.1,20.0.64.0 /secure/MyJiraHome.jspa [c.a.g.r.internal.http.HttpClientFetcher] Unable to perform a request to: https://jira.example.com/rest/gadgets/1.0/g/messagebundle/en_US/gadget.common%2Cgadget.activity.stream
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <jira.example.com> doesn't match any of the subject alternative names: [9598e5ef6b3797492d9596d030f5830f.84ffe945957d674d25825d9e678fb3a4.traefik.default]
```

and 
```
2018-05-01 10:25:36,591 HealthCheck:thread-4 ERROR hoeghh 625x78x2 197uri4 192.168.50.1,20.0.64.0 /rest/troubleshooting/1.0/check/process/ [c.a.t.j.healthcheck.support.GadgetFeedUrlHealthCheck] An error occurred when performing the Gadget feed URL healthcheck
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
```

In ASK we have the following function in docker-entrypoint.sh
```
if [ -f "${CERTIFICATE}" ]; then
  /opt/atlassian/jira/jre/bin/keytool -noprompt -storepass changeit -keystore ${JAVA_CACERTS} -import -file ${CERTIFICATE} -alias CompanyCA
fi
```
Where ${CERTIFICATE} is the location to the certificate mounted on disk 
${JAVA_CACERTS} is the path to cacerts (Default : /opt/atlassian/jira/jre/lib/security/ )

This should be implemented here as well, and controlled by the helm chart.

**Comment by hoeghh** [comment]
The user should define wether or not to import certificates, and be able to define 1 or more certificates to import.

We will do this by creating an enviroment variable like ENABLE_CERT_IMPORT=true|false

then we have a folder containing certs, defined by the user in secrets. If ENABLE_CERT_IMPORT is set to true, we will import all certs in that folder.

**Comment by sami-alajrami** [comment]
@KamranAzeem has this been done in the dockerfile?

**Comment by sheeeng** [comment]
Waiting for test. See if additional SSL certificates are loaded.

* Start Jira with SSL certificates provided.
* Use keytool to show loaded certificates.

**Comment by sheeeng** [comment]
Created four certificates manually under a single directory. Entry point script can load them.

```
openssl req \
    -newkey rsa:2048 -nodes -keyout northwind.key \
    -x509 -days 365 -out northwind.crt \
    -subj "/C=US/ST=California/L=Cupertino/O=Northwind/OU=IT Department/CN=northwind.com"

openssl req \
    -newkey rsa:2048 -nodes -keyout southwind.key \
    -x509 -days 365 -out southwind.pem \
    -subj "/C=US/ST=California/L=Mountain View/O=Southwind/OU=IT Department/CN=southwind.com"

openssl req \
    -newkey rsa:2048 -nodes -keyout eastwind.key \
    -x509 -days 365 -out eastwind.crt \
    -subj "/C=US/ST=California/L=Sunnyvale/O=Eastwind/OU=IT Department/CN=eastwind.com"

openssl req \
    -newkey rsa:2048 -nodes -keyout westwind.key \
    -x509 -days 365 -out westwind.pem \
    -subj "/C=US/ST=California/L=Palo Alto/O=Westwind/OU=IT Department/CN=westwind.com"
```

```text
Importing certificate: /var/atlassian/ssl/eastwind.crt ...
Certificate was added to keystore
Importing certificate: /var/atlassian/ssl/northwind.crt ...
Certificate was added to keystore
Importing certificate: /var/atlassian/ssl/southwind.pem ...
Certificate was added to keystore
Importing certificate: /var/atlassian/ssl/westwind.pem ...
Certificate was added to keystore
```
